version: '2'
services:
  nginx:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./Nginx
    volumes:
      - ./Nginx/logs:/var/log/nginx
    ports:
      - '80:80'

  nest-back:
    build:
      context: ./NestBack
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - /usr/app/node_modules
      - ./NestBack:/usr/app
    command: ['npm', 'run', 'start:dev']

  db:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./Database
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./Database/dev/data:/var/lib/postgresql/data
