version: '2'
services:
  db:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./Database
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./Database/dev/data:/var/lib/postgresql/data

  nest-back:
    build:
      context: ./NestBack
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules
      - ./NestBack:/usr/src/app
    command: ['npm', 'run', 'start:dev']

  react-front:
    build:
      context: ./NextFront
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./NextFront:/usr/src/app
    command: ['npm', 'start']

    environment:
      - WDS_SOCKET_PORT=0
  nginx:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./Nginx
    volumes:
      - ./Nginx/logs:/var/log/nginx
    ports:
      - '80:80'
